### ISSUE TITLE
ENS support shouldn't use a whitelist

### ISSUE THREAD

**Issue by Arachnid** [komputing/KEthereum#103]
Currently ENS support uses a whitelist of ENS TLDs. However, we plan to expand ENS support to many new DNS-based TLDs in the future, and whitelisting is impractical.

A better solution would be to simply try resolving any name containing a dot - if it resolves, it's a valid ENS name!

**Comment by ligi** [comment]
Thanks for raising this - I tried to avoid network/service roundtrips - but yea I should value future-compatibility more than that (especially in current times where network/service roundrips are not as expensive anymore - still being a bit too old-school here) - change contained in 8acd970 and will be released via  0.84.2 today.
