### ISSUE TITLE
ENS resolver responds with wrong address for domain

### ISSUE THREAD

**Issue by abdrasulov** [komputing/KEthereum#130]
Trying to resolve the domain name "deepak.eth":

```kotlin
val address = ens.getAddress(ENSName("deepak.eth"))
```

It responds with address `0x69c488Bcda156379B6661f08A35dB627E5D467Dd`. But the expected address is `0x6942049509693fbb63d7F1395DAe5cFE1CCEc1BA` (https://app.ens.domains/name/deepak.eth/details)

**Comment by ligi** [comment]
what RPC did you use?

**Comment by ligi** [comment]
background: I guess the node you speak to hangs somewhere (e.g. at the merge point as the IN3 nodes do currently) - and so you get a old result

**Comment by abdrasulov** [comment]
> what RPC did you use?

The default one. The ENS instance was initialized like this:

```kotlin
val ens = ENS(getMin3RPC())
```

**Comment by ligi** [comment]
this is the problem then - it uses the incubed RPC - unfortunately the incubed RPC never made it through the merge as blockchains.llc killed the project ;-(
Use another RPC and it should work fine
