### ISSUE TITLE
use KHash instead of `org.walleth.sha3`

### ISSUE THREAD

**Issue by mirceanis** [komputing/KEthereum#65]
[KHash](https://github.com/komputing/KHash) provides implementations for some (if not all) of the hashing methods needed by KEthereum.
Dependencies on any legacy hashing methods should be replaced with KHash.

Using KHash in combination with KEthereum in the same project can create duplicate class conflicts with the current latest versions (0.8 & 0.75.0)

If there is a reason for not using KHash (yet) of which I am unaware, please comment and close this issue.

**Comment by ligi** [comment]
Yes - you are right - this should be done. Just did not yet get around to it - but it was the plan when creating KHash
