### ISSUE TITLE
Testnet support in bip32

### ISSUE THREAD

**Issue by mahdi13** [komputing/KEthereum#67]
https://github.com/komputing/KEthereum/blob/3b69fde6d80ef6e80a632b756a93d5def5998179/bip32/src/main/kotlin/org/kethereum/bip32/model/Constants.kt#L10

The Testnet network could be supported in bip32's ExtendedKey deserialization:
```
internal val xprvTestnet = byteArrayOf(0x04, 0x88.toByte(), 0xAD.toByte(), 0xE4.toByte())
internal val xpubTestnet = byteArrayOf(0x04, 0x35.toByte(), 0x87.toByte(), 0xCF.toByte())
```

And it could be considered in `XPriv.toExtendedKey()` method:
```
    val hasPrivate = when {
        Arrays.equals(type, xprv) -> true
        Arrays.equals(type, xprvTestnet) -> true
        Arrays.equals(type, xpub) -> false
        Arrays.equals(type, xpubTestnet) -> false
        else -> throw KeyException("invalid magic number for an extended key")
    }
```

**Comment by ligi** [comment]
Thanks for the feedback. Pull requests are welcome. I think this is only relevant for Bitcoin right?

**Comment by mahdi13** [comment]
Sure, I'll work on it.
Yes, It's related to Bitcoin. But the `Version Byte` is part of the bip-0032 proposal.

**Comment by ligi** [comment]
great - looking forward to your PR

**Comment by mahdi13** [comment]
I tried my best in #68 , sorry for any mistakes in advanced.
