### ISSUE TITLE
Could not find org.kbignumbers:kbignumbers-jvm:1.0.0-RC1.

### ISSUE THREAD

**Issue by mitfik** [komputing/KEthereum#71]
When trying to use

    implementation 'com.github.komputing:KEthereum:0.76.1'

In Android Studio getting error:

> Could not find org.kbignumbers:kbignumbers-jvm:1.0.0-RC1.
> Searched in the following locations:
>   - https://dl.google.com/dl/android/maven2/org/kbignumbers/kbignumbers-jvm/1.0.0-RC1/kbignumbers-jvm-1.0.0-RC1.pom
>   - https://dl.google.com/dl/android/maven2/org/kbignumbers/kbignumbers-jvm/1.0.0-RC1/kbignumbers-jvm-1.0.0-RC1.jar
>   - https://repo.maven.apache.org/maven2/org/kbignumbers/kbignumbers-jvm/1.0.0-RC1/kbignumbers-jvm-1.0.0-RC1.pom
>   - https://repo.maven.apache.org/maven2/org/kbignumbers/kbignumbers-jvm/1.0.0-RC1/kbignumbers-jvm-1.0.0-RC1.jar
>   - https://dl.bintray.com/terl/lazysodium-maven/org/kbignumbers/kbignumbers-jvm/1.0.0-RC1/kbignumbers-jvm-1.0.0-RC1.pom
>   - https://dl.bintray.com/terl/lazysodium-maven/org/kbignumbers/kbignumbers-jvm/1.0.0-RC1/kbignumbers-jvm-1.0.0-RC1.jar
>   - https://jitpack.io/org/kbignumbers/kbignumbers-jvm/1.0.0-RC1/kbignumbers-jvm-1.0.0-RC1.pom
>   - https://jitpack.io/org/kbignumbers/kbignumbers-jvm/1.0.0-RC1/kbignumbers-jvm-1.0.0-RC1.jar
> Required by:
>     project :app > com.github.komputing:KEthereum:0.76.1 > com.github.komputing.KEthereum:keccak_shortcut:0.76.1 > com.github.komputing.KHash:keccak-jvm:1.0.0-RC2

Seems like there is no 1.0.0-RC2 build on jitpack yet. Any plans to get it there? And in meantime is there any workaround for that issue?

**Comment by ligi** [comment]
Sorry - but I cannot reproduce your problem. Can you share your whole project? There seems to be a dependency on org.kbignumbers which will not exist and I do not see it anywhere in KEthereum

**Comment by friedger** [comment]
It is in here: https://github.com/komputing/KHash/blob/b36db9ec3830ecabdd07ca22053e2c0330780876/keccak/build.gradle

**Comment by ligi** [comment]
thanks! @RiccardoM can you have a look? this seems to be rooted in the multi-platform change
