### ISSUE TITLE
Support EIP-1191

### ISSUE THREAD

**Issue by juli** [komputing/KEthereum#80]
KEthereum is used to automatically check files submitted to [ethereum-lists tokens](https://github.com/ethereum-lists/tokens/)

[EIP-1191](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1191.md) addresses are [rejected](https://github.com/ethereum-lists/tokens/blob/master/src/main/kotlin/org/ethereum/lists/tokens/TokenChecker.kt#L32) by the ethereum-lists CI scripts.

Adding EIP-1191 support to KEthereum will allow to check and accept EIP-1191 addresses for networks that choose to use this format.

Adding EIP-1191 support is simple if the chain id can be obtained from the submitted JSON Files.

**Comment by ligi** [comment]
closed via #85
