### ISSUE TITLE
zksync Support

### ISSUE THREAD

**Issue by chrishobcroft** [komputing/KEthereum#92]
# Introduction

This issue proposes to add support for integrating with [zksync](https://zksync.io) - to provide ways for Kotlin application to reduce the costs of moving Ethereum-based assets.

# Context

![image](https://user-images.githubusercontent.com/2212651/86465443-3f487280-bd4f-11ea-8f2b-06ab4785a349.png)

High gas prices have sparked an increased focus on the use of alternative ways to move ETH / ERC20 / ERC721 tokens around in secure and scalable ways. Rollups and zero-knowledge proofs as a way of reducing the use of Ethereum for , e.g. recently by @vbuterin

https://twitter.com/VitalikButerin/status/1277967505932161027

![image](https://user-images.githubusercontent.com/2212651/86465314-014b4e80-bd4f-11ea-9ea3-913cc047d793.png)

# Scope

To add zksync support to KEthereum, providing functions required to interact with [zksync](https://github.com/matter-labs/zksync).

To cover the following basic functions:

- Get Balance(s)
- Deposit
- Transfer
- Withdraw

# Reference Implementation (Typescript / Javascript)

A reference implementation in javascript is available here: https://github.com/matter-labs/zksync/tree/master/js/zksync.js

This is deployed against Rinkeby here: https://testnet.zksync.io

**Comment by ligi** [comment]
as far as I see zkSync 2.0 is compatible with RPC methods and normal keys:
https://medium.com/matter-labs/zksync-2-0-hello-ethereum-ca48588de179
So I think this can be closed as this way it is supported by KEthereum

**Comment by chrishobcroft** [comment]
Agreed. Closing. Thanks.
